### ISSUE TITLE
新商品登录

### ISSUE THREAD

**Issue by wdcyxxycdw** [TokyoShisenGroup/UTokyoMeru_Back#3]
类型约束见apidog

上传图片待解决
1.找个图床然后只存url
2.自己存储（自己实现一个图床）
3.base64存数据库（太傻逼了）

**Comment by cliecy** [comment]
你妈的，我还得找个图床

**Comment by wdcyxxycdw** [comment]
> 你妈的，我还得找个图床

你他妈的咋每个都要评论一下

**Comment by cliecy** [comment]
> > 你妈的，我还得找个图床
> 
> 你他妈的咋每个都要评论一下

不是，你能发issue，我就不能骂你了吗？

**Comment by wdcyxxycdw** [comment]
图呢？图怎么办你妈的，搞半天这个还没做完

**Comment by cliecy** [comment]
> 这个

你骂我？
